language: objective-c
osx_image: xcode11.5

xcode_project: PDKLocation.xcodeproj 
xcode_scheme: PDKLocation

before_install:
- brew update
- brew tap oclint/formulae
- brew install oclint

script:
- set -o pipefail
- xcodebuild -workspace "PDKLocation.xcworkspace" -scheme "PDKLocation" -destination 'platform=iOS Simulator,name=iPhone 8,OS=13.5' -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGN_ENTITLEMENTS="" CODE_SIGNING_ALLOWED="NO" COMPILER_INDEX_STORE_ENABLE="NO" ARCHS='x86_64' VALID_ARCHS='x86_64' ONLY_ACTIVE_ARCH=NO CLANG_ENABLE_MODULES=YES | tee xcodebuild.log | xcpretty -r json-compilation-database --output compile_commands.json
- oclint-json-compilation-database -v
  -e AFNetworking
  -e AppAuth
  -e Charts
  -e DTMHeatmap
  --
  -disable-rule=PreferEarlyExit
  -disable-rule=LongMethod
  -disable-rule=LongVariableName
  -disable-rule=HighCyclomaticComplexity 
  -disable-rule=HighNPathComplexity
  -disable-rule=HighNcssMethod
  -disable-rule=InvertedLogic
  -disable-rule=DeepNestedBlock
  -disable-rule=TooManyMethods
  -disable-rule=LongClass
  -disable-rule=EmptyIfStatement
- xcodebuild test -scheme "PDKLocation" -workspace "PDKLocation.xcworkspace" -destination 'platform=iOS Simulator,name=iPhone 8,OS=13.5' ARCHS='x86_64' VALID_ARCHS='x86_64' ONLY_ACTIVE_ARCH=NO | xcpretty
